// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Logproto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PushRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"streams")]
        public global::System.Collections.Generic.List<Stream> Streams { get; } = new global::System.Collections.Generic.List<Stream>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Stream : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"labels")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Labels { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"entries")]
        public global::System.Collections.Generic.List<Entry> Entries { get; } = new global::System.Collections.Generic.List<Entry>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Entry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ts")]
        public Timestamp Ts { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"line")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Line { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Timestamp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"seconds")]
        public long Seconds { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nanos")]
        public int Nanos { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
